# Day 6
## Part 1

In [197]:
with open('test.txt', 'r') as file:
    test = np.fromiter(map(int, file.readline().strip().split(',')), dtype=int)

In [207]:
import numpy as np
state = np.zeros(9, dtype= int)
for i in test:
    state[i] += 1
for i in range(16):
    print(state)
    state[6] += state[0]
    state = np.roll(state, -1)
print(state.sum())

[0 1 1 2 1 0 0 0 0]
[1 1 2 1 0 0 1 0 0]
[1 2 1 0 0 1 1 0 1]
[2 1 0 0 1 1 2 1 1]
[1 0 0 1 1 2 2 1 2]
[0 0 1 1 2 2 1 2 1]
[0 1 1 2 2 1 2 1 0]
[1 1 2 2 1 2 2 0 0]
[1 2 2 1 2 2 1 0 1]
[2 2 1 2 2 1 2 1 1]
[2 1 2 2 1 2 3 1 2]
[1 2 2 1 2 3 2 2 2]
[2 2 1 2 3 2 4 2 1]
[2 1 2 3 2 4 4 1 2]
[1 2 3 2 4 4 2 2 2]
[2 3 2 4 4 2 4 2 1]
[3 2 4 4 2 4 5 1 2]
29


In [199]:
test

array([3, 4, 3, 1, 2])